### ISSUE TITLE
Formatter ignores file line endings setting

### ISSUE THREAD

**Issue by dithpri** [janosimas/formatter-astyle#10]
Under Windows, formatting ignores the line-ending setting of the file (LF) and uses the platform default (CRLF).
Might be related to #1

**Comment by dithpri** [comment]
This is an issue with Windows redirection, not really formatter-astyle or astyle.

> When redirection is used on Windows the output will always have Windows line ends. This option will be ignored.

[Upstream documentation](http://astyle.sourceforge.net/astyle.html#_Other_Options)

**Comment by dithpri** [comment]
Although this is not a bug with this package, it could be possibly mitigated by not using redirection but copying to a temp file and formatting that file. It does however feel hacky and would require changes to how the package works, and I don't think that's a good solution

**Comment by janosimas** [comment]
Thanks for the feedback.
