### ISSUE TITLE
cannot pass multiple arguments?

### ISSUE THREAD

**Issue by canfoderiskii** [janosimas/formatter-astyle#2]
formatter-astyle version: 0.2.0
AStyle version: 2.05.1
Atom version: 1.7.2
1. if i only enter one argument (for example, --pad-oper) in formatter-style setting page, the formatter works well when i call 'Formatter: Format code' in the command panel.
2. if i enter 2 or more arguments, like "--style=otbs --indent=spaces=4 --attach-extern-c" (not including quotation marks), after i call 'Formatter: Format code', the whole file contents disappear.

**Comment by janosimas** [comment]
Astyle is altering the orignal file but the formater waits for the formated code in the stdout,
I'm looking into it.

You can use a .astylerc with the --options for now :-/

**Comment by janosimas** [comment]
I committed a new version, it should solve your problem.

**Comment by canfoderiskii** [comment]
tried new verison 0.3.0, multiple arguments works fine now! thank you.
