### ISSUE TITLE
request: read astyle parameters from file

### ISSUE THREAD

**Issue by canfoderiskii** [janosimas/formatter-astyle#3]
Is there any possiblilty that adding a feature that read astyle parameters from file before processing?

The location of parameter file can be configured in the package setting page.

Or more, the package can automactiacally search up from the directory tree for file, whose name is internnaly fixed or flexibly configured, if that file is found, use its content to pass to astyle.

**Comment by janosimas** [comment]
Not sure I understood what you want.

In the settings pane you can configure the arguments, you can use:
--options=/path/to/conf/.astylerc

I'll see how to find a conf file in the project automatically.

**Comment by canfoderiskii** [comment]
@janosimas thank you, finding a conf file in project automatically feature is good enough.

**Comment by janosimas** [comment]
I uploaded a new version, it'll look for a .astylerc file in the root folder of you project.
