### ISSUE TITLE
How to run formatter-astyle?

### ISSUE THREAD

**Issue by MatthewPeterKelly** [janosimas/formatter-astyle#4]
I just downloaded and installed formatter-astyle for Atom, but I cannot figure out how to actually use it to format a file. Perhaps you could add a line to the documentation to either 1) tell us what the default key-binding is, or 2) how to create a key-binding, or 3) which menu we can find the formatting under. Thanks!

**Comment by janosimas** [comment]
I'll see to improve the docs.

the reason there is no doc is that this package is an extension of the [formatter](https://atom.io/packages/formatter).
It provides the keybindings and shortcuts:

``` coffeescript
'atom-text-editor':
  'alt-ctrl-l': 'formatter:format-code'
  'alt-cmd-l': 'formatter:format-code'
```

**Comment by MatthewPeterKelly** [comment]
Ok - that makes sense - Thanks!

Aside:  On Ubuntu, `alt-ctrl-l` is set to lock the computer, so I think that I'll need to change either the key bindings in Ubuntu or in formatter so that I can use both.

**Comment by davydden** [comment]
> It provides the keybindings and shortcuts:

i think it would make sense to mention the short-cuts anyway. I was also trying to figure out how to actually run the formatting...
