### ISSUE TITLE
indent-namespace ignored in option file

### ISSUE THREAD

**Issue by LiZhenhuan1019** [janosimas/formatter-astyle#9]
I have --indent-namepsace option set in my option file in my home folder, and I'm sure that it works if I use astyle directly. But when I use formatter-astyle, only the option of 'Indent namespace' in Settings page have effect, that is, the 'indent-namespace' option in option file is ignnored.

Specifying the option file's location in Settings page doesn't solve this problem. And I found that I must copy the option file to the project's root folder to make it have effect.

**Comment by janosimas** [comment]
I don't have a machine to test right now,
can you check if the option --indent-namepsace work in the command line with an option file?

Maybe the command line options and settings have some conflict the the options file.

**Comment by LiZhenhuan1019** [comment]
Well it works on Linux.

I encountered this problem on Windows with  msys2 which I use to install astyle. It works if I use bash in msys2 but Atom use cmd to execute commands. I guess that's why it doesn't work. 

There are similliar problems on other packages in Atom so now I don't use Atom on Windows. This problem may be avoided by directly downloading the Astyle binary on Windows rather than using msys2, I guess.
